nutrition/urls.py
from django.urls import path
from .views import autocomplete
from .views import add_food
from .views import daily_nutrition_view
from .views import ask_food_question


app_name = 'nutrition'

urlpatterns = [
    path('autocomplete/', autocomplete, name='autocomplete'),
    path('add-food/', add_food, name='add_food'),
    path('daily-nutrition/', daily_nutrition_view, name='daily_nutrition'),
    path('ask-food-question/', ask_food_question, name='ask-food-question'),
]

orf401project/urls.py
# orf401project/urls.py

from django.contrib import admin
from django.urls import include, path
from workout.views import home  # Ensure this is the correct import statement
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),  # This will set 'home' as the homepage view
    path('workout/', include('workout.urls')),    # ... include other app URLs if needed ...
    path('nutrition/', include('nutrition.urls')),
    path('accounts/', include('accounts.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

workout/urls.py
from django.urls import path
from . import views


app_name = 'workout'

urlpatterns = [
    path('add_exercise/', views.add_exercise, name='add_exercise'),
    path('view_exercises/', views.view_exercises, name='view_exercises'),
    path('add_cardio_instance/<int:exercise_id>/', views.add_cardio_workout_instance, name='add_cardio_instance'),
    path('add_strength_instance/<int:exercise_id>/', views.add_strength_workout_instance, name='add_strength_instance'),
    path('exercise/<int:exercise_id>/', views.exercise_detail, name='exercise_detail'),
]

templates/base_generic.html
<!DOCTYPE html>
<html lang="en" style="height: 100%;">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}WellTrack - Your Wellness Tracker{% endblock %}</title>
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
    <style>
        html, body {
            height: 100%;
            margin: 0;
            padding: 0;
            font-family: 'Arial', sans-serif;
            background-color: #ffffff;
            color: #333;
        }
        body {
            display: flex;
            flex-direction: column;
        }
        header, footer {
            background-color: #007BFF;
            color: #ffffff;
            text-align: center;
            padding: 10px 0;
        }
        nav ul {
            padding: 0;
            list-style-type: none;
            display: flex;
            justify-content: center;
            margin: 0;
        }
        nav ul li {
            margin: 0 10px;
        }
        nav ul li a {
            color: #ffffff;
            text-decoration: none;
        }
        main {
            flex: 1 0 auto;
        }
        footer {
            flex-shrink: 0;
        }
        footer p {
            margin: 0;
            font-size: 0.8em;
        }
        @media (max-width: 600px) {
            nav ul {
                flex-direction: column;
            }
            nav ul li {
                margin: 5px 0;
            }
        }
    </style>
</head>
<body>
    <header>
        <h1>WellTrack</h1>
        <nav>
            <ul>
                <li><a href="{% url 'home' %}">Home</a></li>
                <li><a href="{% url 'workout:add_exercise' %}">Add Exercise</a></li>
                <li><a href="{% url 'workout:view_exercises' %}">View Exercises</a></li>
                <li><a href="{% url 'nutrition:add_food' %}">Add Food Item</a></li>
                <li><a href="{% url 'nutrition:daily_nutrition' %}">View Daily Nutrition</a></li>
                <li><a href="{% url 'nutrition:ask-food-question' %}">FoodPal</a></li>
            </ul>
        </nav>
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <footer>
        <p>&copy; {{ year }} WellTrack. All rights reserved.</p>
    </footer>
</body>
</html>
{% block javascript %}
{% endblock %}

templates/home.html
{% extends "base_generic.html" %}

{% load static %}

{% block content %}
<div style="text-align: center;">
    <img src="{% static 'ORF401logo.png' %}" alt="WellTrack Logo" style="width: 400px; height: auto;">
    <h1 style="margin-top: 175px;">Welcome to our revolutionary new application for tracking your health!</h1>
</div>
{% endblock %}